# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-reranker

tasks:
  run:
    cmds:
      - docker run -it --rm --pull always -p 8000:8000 -v ./.cache:/app/.cache {{.REPOSITORY}}

  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest
